SELECT * FROM afdeling LIMIT 40;
SELECT * FROM afdeling LIMIT 60;
CREATE VIEW a AS SELECT * FROM afdeling;
SELECT * FROM afdeling LIMIT 5,50;
SELECT * FROM afdeling LIMIT 5,100;
SELECT * FROM afdeling LIMIT 60 OFFSET 100;
SELECT * FROM afdeling LIMIT 45 OFFSET 100;